name: CI

on: push

env:
  CI_GITHUB_ACTIONS_TOKEN: ${{ secrets.CI_GITHUB_ACTIONS_TOKEN }}

permissions:
  id-token: write
  contents: read

jobs:
  build:
    if: github.ref_name == 'master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ env.CI_GITHUB_ACTIONS_TOKEN || github.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: AWS Authentication
        uses: Vertexvis/actions/aws-auth@main
        with:
          setup-sbt: false
          setup-ecr: false
          setup-profiles: true

      - name: Build and publish
        run: |
          docker run --rm -i \
            -v ${{ github.workspace }}:/app \
            -v $HOME/.aws:/root/.aws \
            -w /app \
            maven:3.8.5-openjdk-17-slim \
            ./build.sh

